apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-recipe-calorie
  namespace: foodfact
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-recipe-calorie
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: food-recipe-calorie
    spec:
      containers:
      - name: gke-test
        image: gcr.io/PROJECT_ID/IMAGE:TAG
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: ${GOOGLE_APPLICATION_CREDENTIALS}
        ports:
        - containerPort: 8080